#  Numpy Quick Tutorial

## What is Numpy?
* Numpy is an open source extension library (package) for Python.
* Numpy is written specifically to work with multidimensional arrays <span style="color:red">(All the elements of the array must be the same type).</span>
* Numpy is designed for scientific computing.
* NumPy is often used along with packages like SciPy (Scientific Python) and matplotlib (plotting library).

## Basics
* Numpy's main class is <tt class="docutils literal"><span class="pre">ndarray</span></tt> which also has an alias <tt class="docutils literal"><span class="pre">array</span></tt>.
* Useful attributes of
an <tt class="docutils literal"><span class="pre">ndarray</span></tt> object are:

    * <tt class="docutils literal"><span class="pre">ndarray.ndim</span></tt>: the number of dimensions of the array.
    
    * <tt class="docutils literal"><span class="pre">ndarray.shape</span></tt>: A tuple of integers showing the size of the array in each dimension.
    
    * <tt class="docutils literal"><span class="pre">ndarray.size</span></tt>: Total number of elements in the array.
    
    * <tt class="docutils literal"><span class="pre">ndarray.dtype</span></tt>: Type of the array elements.

# Important

## A numpy <span style="color:red; font-family: courier;">ndarray</span> is **NOT**  the same as a python <span style="color:red; font-family: courier;">list</span>.



## How to create arrays
* Arrays can be created from Python sequences such as a list or a tuple. The type of resulting array depends on the type of elements in the sequences.
### Examples

In [1]:
a=[1,2,3]
b=[3,2,1]
a+b

[1, 2, 3, 3, 2, 1]

In [2]:
import numpy as np
x=[1,2,5,3,6, 4 ,5 ]
y=np.array(x)
z=np.array([[1,2,3],[9,8,7]]) # Create an array from a list
print(x)
print(y)
print (type(x))
print(type(y))
print(z)

[1, 2, 5, 3, 6, 4, 5]
[ 2  4 10  6 12  8 10]
<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [9 8 7]]


In [9]:
np.array(((1,2,3),(9,8,7))) # Create an array from a tuple

array([[1, 2, 3],
       [9, 8, 7]])

In [3]:
a = np.array([[1,2,3],[9,8,7]]) # Type of array will be int
print(a.dtype)
print(a)

float64
[[1.01 2.   3.  ]
 [9.   8.   7.  ]]


In [11]:
a = np.array([[1,2,3],[9,8,7]],dtype=float) # Specify type explicitly
a.dtype

dtype('float64')

* The function <tt class="docutils literal"><span class="pre">zero</span></tt> creates arrays of zeros.

In [12]:
np.zeros((3,7)) # Create array of zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

* The function <tt class="docutils literal"><span class="pre">ones</span></tt> creates arrays of ones.

In [13]:
np.ones((3,2)) # Create array of ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

* The function <tt class="docutils literal"><span class="pre">arange</span></tt> creates sequence of numbers.

In [5]:
np.arange( 0, 5, .4 ) # Create array from a sequence of numbers

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8])

* The function <tt class="docutils literal"><span class="pre">linspace</span></tt> can also create sequence of numbers.

In [15]:
np.linspace(.1,.7,5 ) # Create 5 linearly spaced numbers from .1 to .7

array([0.1 , 0.25, 0.4 , 0.55, 0.7 ])

<a id="I_indexterm4_d1e5084" class="indexterm"></a><a id="I_indexterm4_d1e5085" class="indexterm"></a><a id="I_indexterm4_d1e5086" class="indexterm"></a></p><div class="table"><a id="table_array_ctor"></a><p class="title">Array creation functions</p><div class="table-contents"><table summary="Array creation functions" style="border-collapse: collapse;border-top: 0.5pt solid ; border-bottom: 0.5pt solid ; border-left: 0.5pt solid ; border-right: 0.5pt solid ; "><colgroup><col width="1.5in"><col></colgroup><thead><tr><th style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; ">Function</th><th style="border-bottom: 0.5pt solid ; ">Description</th></tr></thead><tbody><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><code class="literal">array</code></td><td style="border-bottom: 0.5pt solid ; ">Convert input data (list, tuple, or other sequence
              type) to an ndarray either by inferring a dtype or explicitly
              specifying a dtype. Copies the input data by default.</td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><a id="I_indexterm4_d1e5108" class="indexterm"></a><code class="literal">asarray</code></td><td style="border-bottom: 0.5pt solid ; ">Convert input to ndarray, but do not copy if the input is
              already an ndarray</td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><a id="I_indexterm4_d1e5117" class="indexterm"></a><code class="literal">arange</code></td><td style="border-bottom: 0.5pt solid ; ">Like the built-in <code class="literal">range</code> but returns an ndarray instead
              of a list.</td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><code class="literal">ones</code></td><td style="border-bottom: 0.5pt solid ; ">Produce an array of all 1’s.
              </td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><code class="literal">ones_like</code></td><td style="border-bottom: 0.5pt solid ; ">Produces a ones array of the same shape and data type as the given array</td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><code class="literal">zeros</code></td><td style="border-bottom: 0.5pt solid ; ">Produce an array of all 0's.</td></tr><tr><td style="border-right: 0.5pt solid ; border-bottom: 0.5pt solid ; "><code class="literal">zeros_like</code></td><td style="border-bottom: 0.5pt solid ; ">Produces an array of all zeros of the same shape and data type as the given array <tr><td style="border-right: 0.5pt solid ; "><code class="literal">identity</code></td><td style="">Create a square identity matrix </td></tr></tbody></table></div></div></div>

## Shape Manipulation
* The function <tt class="docutils literal"><span class="pre">reshape</span></tt> changes the shape of an array.

In [7]:
a=np.linspace(1,6,6 ) # Create a 1 by 6 array
b=a.reshape(2,3) # Reshape the array into a 3 by 2 array
print("a = ",a)
print("b = ",b)

a =  [1. 2. 3. 4. 5. 6.]
b =  [[1. 2. 3.]
 [4. 5. 6.]]


* The function <tt class="docutils literal"><span class="pre">ravel</span></tt> flattens an array.

In [8]:
a = np.array([[1,2,3],[9,8,7]]) # create a 2 by 3 array
b=a.ravel()
print("a = ",a)
print("b = ",b)

a =  [[ 1  4  9]
 [81 64 49]]
b =  [ 1  4  9 81 64 49]


## Universal Functions
* Universal functions are familiar functions such as <tt class="docutils literal"><span class="pre">sin, cos, exp. sqrt.</span></tt> These functions operate elementwise on an array and produce another array as output.

In [18]:
a = np.array([[1,2,3],[9,8,7]]) # create a 2 by 3 array
b = np.sin(a)
print (b)

[[0.84147098 0.90929743 0.14112001]
 [0.41211849 0.98935825 0.6569866 ]]


## Basic Array Operations
<span style="color:red; background-color:#aaaaaa; font-size:24px; line-height:12px">NOTE :</span>
All arithmetic operations in numpy are applied **elementwise**. This includes multiplication and division of arrays. **The matrix product of two arrays should be performed by using the <tt class="docutils literal"><span class="pre">dot</span></tt> function.** 


* Scalar operations

In [9]:
a = np.array([1, 2, 3, 4])
a+10  # Scalar, 5, is added to every element of array

array([11, 12, 13, 14])

In [20]:
a = np.array([1, 2, 3, 4])
a*3  # Every element of array is multiplied by the scalar

array([ 3,  6,  9, 12])

In [11]:
a = np.array([1, 2, 3, 4])
ia/3 # Every element of array is divided by the scalar

TypeError: only size-1 arrays can be converted to Python scalars

* Elementwise Array operations

In [22]:
a=np.array([[1,2,3],[9,8,7]])
b=np.array([[6,5,4],[2,4,6]])
print("a= ",a)
print("b= ",b)
c=a*b # Elementwise multiplication
print("c= ",c)
d=np.dot(a,b) #Notice: this will create an error
print(d)

a=  [[1 2 3]
 [9 8 7]]
b=  [[6 5 4]
 [2 4 6]]
c=  [[ 6 10 12]
 [18 32 42]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [24]:
a=np.array([[1,2,3],[9,8,7]])
b=np.array([[6,5,4],[2,4,6]])
a/b # Elementwise division

array([[0.16666667, 0.4       , 0.75      ],
       [4.5       , 2.        , 1.16666667]])

* Mathematical Array operations vs. Elementwise Array operations

In [23]:
a=np.array([[1,2],[9,8]])
b=np.array([[6,5],[2,4]])
c=a*b # Elementwise multiplication
d=np.dot(a,b) # Mathematical multiplication
print("c = ",c)
print("d = ",d)

c =  [[ 6 10]
 [18 32]]
d =  [[10 13]
 [70 77]]


## Links to numpy tutorials
* http://www.scipy-lectures.org/intro/numpy/numpy.html
* https://github.com/Pybonacci/scipy-lecture-notes-ES/blob/master/intro/numpy/operations.rst
* https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/ch04.html


